#include <stdio.h>
#include "Rte.h"
#include "App_SWC.h" // RTE cần gọi các hàm của Application

/*It's regarded as a runnable entity in the RTE. Manythings to do here, so keep only runnable wrappers in this file*/

// /**
//  * @brief RTE implementation for the Sender-Receiver API Rte_Write_Signal_EngineSpeed.
//  * This function is called by the SW-C. It takes the data and passes it down
//  * to the correct BSW module (in this case, COM).
//  * @param data The application data to be sent.
//  * @return E_OK on success.
//  */
// Std_ReturnType Rte_Write_Signal_EngineSpeed(uint16 data) {
//     printf("[RTE] Goi Com_SendSignal_EngineSpeed() tu App_SWC\n");
//     // RTE ánh xạ lời gọi từ SW-C xuống module BSW tương ứng
//     Com_SendSignal_EngineSpeed(data);
//     return 0; // E_OK
// }

// /**
//  * @brief RTE implementation for the Sender-Receiver API Rte_Read_Signal_VehicleSpeed.
//  * This function is called by the SW-C. It gets the data from the correct
//  * BSW module and returns it to the application.
//  * @param data Pointer to store the received application data.
//  * @return E_OK on success.
//  */
// Std_ReturnType Rte_Read_Signal_VehicleSpeed(uint16* data) {
//     printf("[RTE] Goi Com_ReceiveSignal_VehicleSpeed() cho App_SWC\n");
//     // RTE ánh xạ lời gọi từ SW-C xuống module BSW tương ứng
//     Com_ReceiveSignal_VehicleSpeed(data);
//     return 0; // E_OK
// }

/**
 * @brief This is the runnable entity generated by the RTE.
 * The OS/Scheduler will call this function periodically.
 * This function, in turn, calls the actual implementation inside the SW-C.
 */
void Rte_App_Task_Tx_runnable(void) {
    // RTE gọi vào hàm thực thi của SW-C
    App_Task_Tx();
}

/**
 * @brief This is the runnable entity generated by the RTE.
 * The OS/Scheduler will call this function periodically.
 * This function, in turn, calls the actual implementation inside the SW-C.
 */
void Rte_App_Task_Rx_runnable(void) {
     // RTE gọi vào hàm thực thi của SW-C
    App_Task_Rx();
}